### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by xnanodax** [jeffliang0318/Jtsy#2]
# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

# Comments:

**Comment by xnanodax** [comment]
Don't forget to add bullets to each MVP!

**Comment by jeffliang0318** [comment]
* put bullets
* put estimate time

**Comment by xnanodax** [comment]
Awesome!
