### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by xnanodax** [jeffliang0318/Jtsy#3]
# Database Schema
- [x] Contains correct datatypes
  - NOTE: You may want the price to be a float, not an integer if you want cents :)
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - NOTE: I see that you have listed the associations. This bullets points should be more like `shopping_cart_id` references `shopping_cart`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] column names are bolded
    - [x] columns names are lowercased and snaked_cased
    - [x] the names of the column names should be placed in `back_ticks`

# Comments:
- [x] don't forget to add `created_at` and `updated_at` fields to each of your tables

**Comment by jeffliang0318** [comment]
- Add `created_at`, `updated_at` to each tables

- change `price` datatype to float

- using `user_id`, `shopping_cart_id`, and `product_id` on association 

- Apply indexed constrain

- Placed `back_ticks` on the column names

**Comment by xnanodax** [comment]
- [x] change `create_at` and `update_at` to `created_at` and `updated_at`

- [x] You may to change product's `description` from `string` to `text` so it can be longer than 255 characters.

- [x] What is the reasoning behind having a shopping cart id for a product?

- [x] Do you want a user to review an item multiple times? If not, you should have a unique constraint.

- [x] ❗️ What was the reason behind adding a shopping_cart_id to the products table?? What if there is one product with multiple quantities that two users want to add?

**Comment by jeffliang0318** [comment]
* First I thought if item bought by someone, it is not available for other user, updated the shopping cart and product so now product can buy from different users

**Comment by xnanodax** [comment]
Looks good!
