### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by xnanodax** [jeffliang0318/Jtsy#7]
# Wireframes
- [ ] Every component listed in the component hierarchy wiki page has at least one wireframe
- [ ] Every MVPs listed on the MVP wiki page has at least one wireframe
- [ ] Every route listed on the route wiki page has at least one wireframe
- [x] Contains Containers
- [x] Contains Lists
- [x] Contains ListItems
- [ ] Correctly formatted
    - [x] Wireframe images display on the page
    - [ ] Every wireframe has a header title

Note: 
+ They have enough wireframes. Pretend you are using their site through the wireframes and try to make sure they have all of the functionality
+ They contain some way of designating components and it looks like all major components are accounted for (arrows, etc)
+ They have decent spacial awareness

# Comments:

**Comment by jeffliang0318** [comment]
Should I put the wireframes in the component in the hierarchy as bluebird example or in separate page?

**Comment by xnanodax** [comment]
You should place in the component hierarchy :) I will now close this issue because this does not need to be a separate page!
