### ISSUE TITLE
Product Listings

### ISSUE THREAD

**Issue by jeffliang0318** [jeffliang0318/Jtsy#9]
- [x]  Backend: DB, model, controller, views

- [x]  Redux Loop: ajax, actions, reducer

- [x]  Presentational Components

- [x]  Adequate styling

- [x]  Smooth, bug-free navigation

- [x]  Seeded with info to demonstrate this feature

- [x] User can see products list without login

- [x] User need to login to create, edit, delete products

**Comment by xnanodax** [comment]
I would improve the show page :) Your functionality is there. Let's get the styling done :)

**Comment by xnanodax** [comment]
Product listing looks good! The core functionality is there.

- [ ] In the case you come back to refactor this code, I suggest to pad the price amount to have all the digits. Example: `20.5` Did you mean `20.50`? 
![screen shot 2018-04-13 at 3 19 58 pm](https://user-images.githubusercontent.com/20424731/38760111-5b5105a6-3f2e-11e8-945f-cacd3b0cf636.png)

I still see this issue on this product: 
https://jtsy.herokuapp.com/#/product/3
